version: '3'

services:
  mysql:
    image: 'mysql:8'
    container_name: 'java-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: 'oaid'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'Password123#'
    ports:
      - "8088:3306"

  app:
    build: ./
    container_name: 'planninganddoing'
    ports:
      - '8080:8080'