version: '3.3'

services:
  mysqldb:
    image: 'mysql:8.0'
    restart: 'always'

    container_name: 'mysqldb'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'oaid'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'Password123#'
    command: 'mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci'

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: 'mysqldb'
      MYSQL_PORT: '3306'
      MYSQL_USER: 'springuser'
      MYSQL_PASSWORD: 'Password123#'
    container_name: 'application'
    ports:
      - '8080:8080'
    restart: 'unless-stopped'
    depends_on:
      - 'mysqldb'